version: "3"  
services:  
  nginx: 
    image: nginx:latest
    restart: always
    container_name: dev_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8001:80
  orders:
    container_name: dev_orders
    restart: always
    build:
      context: ./orders
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  payments:
    container_name: dev_payments
    restart: always
    build:
      context: ./payments
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80